version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cardiorisk_api
      MYSQL_USER: dockerapi
      MYSQL_PASSWORD: Docker123!
    ports:
      - "4306:4306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  fuzzy-api:
    build: .
    container_name: fuzzy-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

