name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Set environment variables
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: dockerapi
        DB_PASSWORD: Docker123!
        DB_NAME: cardiorisk_api
      run: echo "Environment variables set for CI"

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run flake8 (PEP8 check)
      run: flake8 src/ --exit-zero

    - name: Run unit tests with pytest
      run: pytest tests/
